const projects=[
{name:'Estilo Boa Viagem',start:'2025-07-01',end:'2027-02-28'},
{name:'Wave Boa Viagem',start:'2026-05-01',end:'2028-12-31'},
{name:'Viva Vida Jardim Botânico',start:'2025-07-01',end:'2027-11-30'},
{name:'Direcional Praia',start:'2024-01-01',end:'2025-12-31'},
{name:'Conquista Jaboatão',start:'2025-04-01',end:'2027-07-31'},
{name:'Conquista Paulista Residence',start:'2026-05-01',end:'2028-12-31'},
{name:'Viva Vida São Lourenço',start:'2023-01-01',end:'2026-05-31'},
{name:'Viva Vida Brisas de Igarassu',start:'2024-05-01',end:'2026-11-30'},
{name:'Viva Vida Direcional Primavera',start:'2026-05-01',end:'2028-08-31'}];
const policies={Diamante:{ps:.25,total:.50,parcel:.20},Ouro:{ps:.20,total:.50,parcel:.20},Prata:{ps:.18,total:.48,parcel:.18},Bronze:{ps:.15,total:.45,parcel:.15},'Aço':{ps:.12,total:.40,parcel:.10}};
const $=id=>document.getElementById(id), money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), pct=v=>`${(v*100).toFixed(1).replace('.',',')}%`, val=id=>Number($(id).value)||0;
function addMonths(d,n){const x=new Date(d+'T12:00:00');x.setMonth(x.getMonth()+n);return x.toISOString().slice(0,10)}
function addDays(d,n){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function init(){projects.forEach((p,i)=>$('project').add(new Option(p.name,i)));Object.keys(policies).forEach(x=>$('policy').add(new Option(x,x)));$('policy').value='Ouro';const today=new Date().toISOString().slice(0,10);$('proposalDate').value=today;$('ccDate').value=today;$('firstMonthly').value=addMonths(today,1);['signals','annuals'].forEach((id)=>{const annual=id==='annuals';for(let i=1;i<=3;i++)$(id).insertAdjacentHTML('beforeend',`<label>${annual?'Anual':'Sinal'} ${i}<input id="${annual?'annual':'signal'}${i}" type="number" min="0" step="0.01"><input aria-label="Data" id="${annual?'annualDate':'signalDate'}${i}" type="date"></label>`)});syncProject();syncDates();syncPolicy()}
function syncProject(){const p=projects[$('project').value];$('startWork').value=p.start;$('endWork').value=p.end}
function syncDates(){const d=$('proposalDate').value;if(!d)return;[30,60,90].forEach((n,i)=>$(`signalDate${i+1}`).value=addDays(d,n));[12,24,36].forEach((n,i)=>$(`annualDate${i+1}`).value=addMonths(d,n))}
function syncPolicy(){const p=policies[$('policy').value];$('policyInfo').textContent=`${$('policy').value}: ${pct(p.ps)} de Pro Soluto • até 84x • comprometimento total até ${pct(p.total)} • parcela PS até ${pct(p.parcel)}`}
function baseData(){const p=policies[$('policy').value], sale=val('sale'), benefits=val('financing')+val('subsidy')+val('fgts')+val('campaign')+val('otherDiscount'), extras=[1,2,3].reduce((s,i)=>s+val('signal'+i)+val('annual'+i),0), cc=val('cc');return{p,sale,benefits,extras,cc,rawPS:Math.max(0,sale-benefits-cc-extras),target:sale*p.ps}}
function suggest(){const d=baseData();const ideal=Math.max(0,d.sale-d.benefits-d.extras-d.target);$('cc').value=ideal.toFixed(2);calculate()}
function calculate(){const d=baseData(), income=val('income'), term=Math.min(84,Math.max(1,Math.round(val('term')||84))), first=$('firstMonthly').value||$('proposalDate').value,end=$('endWork').value, bank=val('bankPayment');$('term').value=term;const principal=d.rawPS;let dfs=[],acc=1,rates=[];for(let i=0;i<term;i++){const date=addMonths(first,i),rate=date<=end?.005:.015;acc*=1+rate;dfs.push(1/acc);rates.push({date,rate})}const payment=principal/(dfs.reduce((a,b)=>a+b,0)||1);const total=payment*term;const psComp=income?payment/income:0,totalComp=income?(payment+bank)/income:0;let status=principal<=d.target+.01&&psComp<=d.p.parcel+.00001&&totalComp<=d.p.total+.00001?'APROVADO':'REVISAR';$('psTarget').textContent=`${money(d.target)} (${pct(d.p.ps)})`;$('monthly').textContent=money(payment);$('totalCorrected').textContent=money(total);$('status').textContent=status;$('status').className=status==='APROVADO'?'ok':'bad';let alerts=[];if(principal>d.target+.01)alerts.push(`O saldo de Pro Soluto está ${money(principal-d.target)} acima da política.`);if(psComp>d.p.parcel)alerts.push(`A parcela PS compromete ${pct(psComp)} da renda, limite ${pct(d.p.parcel)}.`);if(totalComp>d.p.total)alerts.push(`O comprometimento total é ${pct(totalComp)}, limite ${pct(d.p.total)}.`);if(!alerts.length)alerts.push('Fluxo dentro dos limites informados para a classificação selecionada.');$('alerts').innerHTML=alerts.map(x=>`<p>${x}</p>`).join('');$('schedule').innerHTML=rates.map((r,i)=>`<tr><td>${i+1}</td><td>${new Date(r.date+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${r.date<=end?'Obra':'Pós-obra'}</td><td>${pct(r.rate)}</td><td>${money(payment)}</td><td>${pct(psComp)}</td><td>${pct(totalComp)}</td></tr>`).join('')}
$('project').addEventListener('change',syncProject);$('proposalDate').addEventListener('change',syncDates);$('policy').addEventListener('change',syncPolicy);$('suggestBtn').addEventListener('click',suggest);$('calcBtn').addEventListener('click',calculate);$('printBtn').addEventListener('click',()=>window.print());$('resetBtn').addEventListener('click',()=>location.reload());init();
